#%RAML 1.0
title: Password Recovery API
baseUri: hb://password-recovery

# Copyright (c) 2017 Magomed Abdurakhmanov, Hypertino
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

types:
  InitPasswordRecovery:
    type: object
    properties:
      template?: string
      email?: string
      language?: string
      ip_address?: string

/password-recoveries:
  post:
    description: |
      Init user password recovery (send email/sms, etc).
    body:
      application/json: InitPasswordRecovery
    responses:
      202:
